### ISSUE TITLE
where is "Recurrent" in tensorflow 1.5?

### ISSUE THREAD

**Issue by adrienbruno** [datalogue/keras-attention#25]
Hello!
Your code seems a good job to understand attention technics!  
I'm working on tensorflow last version 1.5 including keras.  My issue is simple , I don't find  Recurrent to import...       
in the code:

import tensorflow as tf
from tensorflow.python.keras import backend as K
from tensorflow.python.keras import regularizers, constraints, initializers, activations
from tensorflow.python.keras.layers.recurrent import Recurrent
      the error is here
from tensorflow.python.keras.layers import InputSpec
from .tdd import _time_distributed_dense
tfPrint = lambda d, T: tf.Print(input_=T, data=[T, tf.shape(T)], message=d)
class AttentionDecoder(Recurrent):.....

the error  is the following
  File "/home/adrien/Tensorflow/Projets/keras-attention/models/custom_recurrents.py", line 4, in <module>
    from tensorflow.python.keras.layers import Recurrent
ImportError: cannot import name 'Recurrent'

I thank you in advance

**Comment by adrienbruno** [comment]
Seems to be ok with:
  from tensorflow.python.keras._impl.keras.layers.recurrent import Recurrent

looking to :  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/__init__.py

**Comment by mahdiyeh-xx** [comment]
I am using tf 2.2 with the same problem:

 from keras.layers.recurrent import Recurrent, _time_distributed_dense
ImportError: cannot import name 'Recurrent'

**Comment by caiyuan11** [comment]
> 

I also have the same problem using keras 2.8

**Comment by QiWang233** [comment]
have anyone sovled this problem?
